# Generated by Django 3.2.8 on 2021-10-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotaurus', '0002_auto_20211014_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
