# Generated by Django 3.2.8 on 2021-10-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotaurus', '0004_auto_20211016_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPriceHistory',
        ),
    ]
