# Generated by Django 3.2.8 on 2021-10-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotaurus', '0005_delete_stockpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangotaurus.stock')),
            ],
        ),
    ]
