# Generated by Django 3.2.8 on 2021-10-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotaurus', '0006_stockpricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='StockPriceHistory',
        ),
    ]
