# Generated by Django 3.2.8 on 2021-10-26 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangotaurus', '0010_auto_20211026_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(default=-999, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(default=-999, on_delete=django.db.models.deletion.SET_DEFAULT, to='djangotaurus.stock'),
        ),
    ]
